//
//  TBSDKAlbum.h
//  TapsbookSDK
//
//  Created by Xinrong Guo on 14-3-28.
//  Copyright (c) 2014年 tapsbook. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <TapsbookSDK/TBImage.h>
#import <TapsbookSDK/TBProduct.h>

/**
 A TBSDKAlbum object represents a photo book that is created by user. 

 To allow your app user see a list of photo books created by the user, use TBSDKAlbum to fetch the photo book metadata such as the book title, cover image, created date and ordered date.
 
 TBSDKAlbum should be created by TBSDKAlbumManager and you should not attempt to create a TBSDKAlbum object. **TBSDKAlbum properties are immutable**. These property value are dynimically generated by TBSDKAlbumManager, are only provided for your app's displaying purpose.

*/
@interface TBSDKAlbum : NSObject

@property (assign, nonatomic) long long ID;

///---------------------------------------
/// @name Book Cover
///---------------------------------------

@property (assign, nonatomic) TBProductType productType;

/** Book Title, this is the title user entered on the book cover
 */
@property (copy, nonatomic) NSString *title;

/** Tag when you created the book. You can use tag to categorize your books.
 */
@property (assign, nonatomic) NSInteger tag;

@property (strong, nonatomic) TBImage *coverImage;

/** The path where SDK saves the rendered cover page image
 */
@property (strong, nonatomic) NSString *coverPageImagePath;

/** Number of pages
 */
@property (assign, nonatomic) NSInteger numberOfPages;

/** The time book was created
 */
@property (strong, nonatomic) NSDate *createdDate;

/** The time book was modified
 */
@property (strong, nonatomic) NSDate *modifiedDate;

/** The time book was printed, return Nil if book has not been ordered before
 */
@property (strong, nonatomic) NSDate *printedDate;

//private API as placeholder
@property (strong, nonatomic) NSDictionary * productOptions;

///---------------------------------------
/// @name Book Photo Contents
///---------------------------------------

/** Number of Photos in the book
 */
@property (assign, nonatomic) NSInteger numberOfPhotos;

/** Array of TBImages (Photos) in the book
 */
@property (strong, nonatomic) NSArray *images;
@property (strong, nonatomic) NSArray *hiddenImages;

@property (copy, nonatomic) NSString *identifier;
@property (strong, nonatomic) id userData; // Anything you like

@end
